
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://eqpdeplnjqqfhksfswik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcGRlcGxuanFxZmhrc2Zzd2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTg0ODAsImV4cCI6MjA1ODk5NDQ4MH0.5zqKhqNF-mgB48paUGHs-lZTr0lTeNbcYydQN4uj6Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
